start java -jar ucs-admin.jar
start java -jar ucs-auth.jar
start java -jar ucs-desk.jar
start java -jar ucs-develop.jar
start java -jar ucs-log.jar
start java -jar ucs-resource.jar
start java -jar ucs-system.jar
start java -jar ucs-user.jar
start java -jar ucs-gateway.jar